name: Bump Version

on:
  create:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to bump version on'
        required: true
      version:
        description: 'Version to bump to'
        required: true

jobs:
  bump-version-manual:
    name: Bump Version (Manual)
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/create-version-bump-pr.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
    secrets: inherit

  created-ref:
    name: Bump Version On New Git Ref
    if: github.event_name == 'create'
     # && github.repository == 'opensearch-project/opensearch-java'
    runs-on: ubuntu-latest
    steps:
      - name: Determine Git Ref Type
        id: type
        run: |
          set -ex

          echo "Determining type of Git ref: ${GITHUB_REF}"

          is_minor_indev_branch=false
          is_patch_indev_branch=false
          is_version_tag=false
          major="0"
          minor="0"
          patch="0"
          is_major_bump=false
          is_minor_bump=false
          
          if [[ "${GITHUB_REF}" =~ ^refs/heads/([0-9]+)\.x$ ]]; then
            is_minor_indev_branch=true
            major="${BASH_REMATCH[1]}"
          fi
          
          if [[ "${GITHUB_REF}" =~ ^refs/heads/([0-9]+)\.([0-9]+)$ ]]; then
            is_patch_indev_branch=true
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
          fi
          
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            is_version_tag=true
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"

            if [[ "${patch}" == "0" ]]; then
              is_minor_bump=true

              if [[ "${minor}" == "0" ]]; then
                is_major_bump=true
              fi
            fi
          fi
          
          {
            echo "is_minor_indev_branch=${is_minor_indev_branch}"
            echo "is_patch_indev_branch=${is_patch_indev_branch}"
            echo "is_version_tag=${is_version_tag}"
            echo "major=${major}"
            echo "minor=${minor}"
            echo "patch=${patch}"
            echo "next_major_version=$((major + 1)).0.0"
            echo "next_minor_version=${major}.$((minor + 1)).0"
            echo "next_patch_version=${major}.${minor}.$((patch + 1))"
            echo "minor_indev_branch_name=${major}.x"
            echo "patch_indev_branch_name=${major}.${minor}"
            echo "is_major_bump=${is_major_bump}"
            echo "is_minor_bump=${is_minor_bump}"
          } | tee -a "${GITHUB_OUTPUT}"

      - name: Generate GitHub App Token
        id: github_app_token
        uses: actions/create-github-app-token@v2
        if: steps.type.outputs.is_major_bump == 'true' || steps.type.outputs.is_minor_bump == 'true'
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Create ${{ steps.type.outputs.minor_indev_branch_name }} Branch
        if: steps.type.outputs.is_major_bump == 'true'
        uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: ${{ steps.type.outputs.minor_indev_branch_name }}
          sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ steps.github_app_token.outputs.token }}

      - name: Create ${{ steps.type.outputs.patch_indev_branch_name }} Branch
        if: steps.type.outputs.is_minor_bump == 'true'
        uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: ${{ steps.type.outputs.patch_indev_branch_name }}
          sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ steps.github_app_token.outputs.token }}
    outputs:
      is_minor_indev_branch: ${{ steps.type.outputs.is_minor_indev_branch }}
      is_patch_indev_branch: ${{ steps.type.outputs.is_patch_indev_branch }}
      is_version_tag: ${{ steps.type.outputs.is_version_tag }}
      major: ${{ steps.type.outputs.major }}
      minor: ${{ steps.type.outputs.minor }}
      patch: ${{ steps.type.outputs.patch }}
      next_major_version: ${{ steps.type.outputs.next_major_version }}
      next_minor_version: ${{ steps.type.outputs.next_minor_version }}
      next_patch_version: ${{ steps.type.outputs.next_patch_version }}
      minor_indev_branch_name: ${{ steps.type.outputs.minor_indev_branch_name }}
      patch_indev_branch_name: ${{ steps.type.outputs.patch_indev_branch_name }}
      is_major_bump: ${{ steps.type.outputs.is_major_bump }}
      is_minor_bump: ${{ steps.type.outputs.is_minor_bump }}

  bump-patch-indev-branch:
    name: Bump Version on Patch InDev Branch
    needs: created-ref
    if: needs.created-ref.outputs.is_patch_indev_branch == 'true' || needs.created-ref.outputs.is_version_tag == 'true'
    uses: ./.github/workflows/create-version-bump-pr.yml
    with:
      branch: ${{ needs.created-ref.outputs.patch_indev_branch_name }}
      version: ${{ needs.created-ref.outputs.next_patch_version }}
    secrets: inherit

  bump-minor-indev-branch:
    name: Bump Version On Minor InDev Branch
    needs: created-ref
    if: needs.created-ref.outputs.is_minor_indev_branch == 'true' || needs.created-ref.outputs.is_minor_bump == 'true'
    uses: ./.github/workflows/create-version-bump-pr.yml
    with:
      branch: ${{ needs.created-ref.outputs.minor_indev_branch_name }}
      version: ${{ needs.created-ref.outputs.next_minor_version }}
    secrets: inherit

  bump-major-indev-branch:
    name: Bump Version On Major InDev Branch (main)
    needs: created-ref
    if: needs.created-ref.outputs.is_major_bump == 'true'
    uses: ./.github/workflows/create-version-bump-pr.yml
    with:
      branch: main
      version: ${{ needs.created-ref.outputs.next_major_version }}
    secrets: inherit