name: Create Version Bump Pull Request

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to bump version on'
        required: true
        type: string
      version:
        description: 'Version to bump to'
        required: true
        type: string
    secrets:
      APP_ID:
        description: 'GitHub App ID'
        required: true
      APP_PRIVATE_KEY:
        description: 'GitHub App Private Key'
        required: true

jobs:
  create-version-bump-pr:
    name: Create Version Bump Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: github_app_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Bump Version To ${{ inputs.version }}
        run: bash .ci/bump-version.sh "$VERSION"
        env:
          VERSION: ${{ inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          base: ${{ inputs.branch }}
          branch: 'feat/${{ inputs.branch }}/bump-version'
          commit-message: Bump version to ${{ inputs.version }}
          signoff: true
          delete-branch: true
          labels: |
              autocut
          title: '[AUTO] Bump version on `${{ inputs.branch }}` to `${{ inputs.version }}`'
          body: |
              Bumping version on `${{ inputs.branch }}` to `${{ inputs.version }}`.